[package]
name = "ccinp-extractor"
version = "0.1.0"
edition = "2018"

[dependencies]
mupdf = "0.3.0"

[dependencies.hyper]
version = "0.14"
features = ["http1", "server", "tcp"]

[dependencies.tokio]
version = "1"
features = ["fs", "rt", "macros"]
